var markerData = [
  {
    id: 1,
    lat: 53.80165,
    lng: -1.54711,
    place: "Leeds City Museum",
    website: "https://citymuseum.leeds.gov.uk/",
    details: "Millennium Square, Leeds LS2 8BH",
    reopeningtime: "Undeclared/Closed",
    type: "museum",
  },
  {
    id: 2,
    lat: 53.79161,
    lng: -1.531,
    place: "Royal Armouries Museum",
    website: "royalarmouries.org",
    details: "Armouries Dr, Leeds LS10 1LT",
    reopeningtime: "2021.5.19",
    type: "museum",
  },
  {
    id: 3,
    lat: 53.79994,
    lng: -1.54826,
    place: "Leeds Art Gallery",
    website: "museumsandgalleries.leeds.gov.uk",
    details: "The Headrow, Leeds LS1 3AA",
    reopeningtime: "Undeclared/Closed",
    type: "gallery",
  },
  {
    id: 4,
    lat: 53.95995,
    lng: -1.08333,
    place: "Whitewall Galleries York",
    website: "www.whitewallgalleries.com",
    details: "9 Davygate, York YO1 8QR",
    reopeningtime: "Opening",
    type: "gallery",
  },
  {
    id: 5,
    lat: 53.80017,
    lng: -1.54027,
    place: "The Domino",
    website: "www.thedomino.co.uk",
    details: "7 Grand Arcade, Leeds LS1 6PG",
    reopeningtime: "2021.5.21",
    type: "club",
  },
];
